
-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Users)
create type user_role as enum ('admin', 'photographer', 'buyer');

create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role user_role default 'buyer',
  stripe_account_id text, -- For photographers
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

-- 2. ALBUMS
create table public.albums (
  id uuid default uuid_generate_v4() primary key,
  photographer_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  cover_image_url text,
  price numeric(10, 2) default 0, -- Price for full album
  is_published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Albums
alter table public.albums enable row level security;
create policy "Published albums are viewable by everyone" on public.albums for select using (is_published = true);
create policy "Photographers can see their own albums (even unpublished)" on public.albums for select using (auth.uid() = photographer_id);
create policy "Photographers can insert their own albums" on public.albums for insert with check (auth.uid() = photographer_id);
create policy "Photographers can update their own albums" on public.albums for update using (auth.uid() = photographer_id);

-- 3. PHOTOS
create table public.photos (
  id uuid default uuid_generate_v4() primary key,
  album_id uuid references public.albums(id) not null,
  title text,
  watermarked_url text not null, -- Publicly accessible
  original_url text, -- Private, requires purchase
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Photos
alter table public.photos enable row level security;
create policy "Watermarked photos are viewable by everyone" on public.photos for select using (true);
-- Access to original_url is tricky via simple RLS if we want column-level security. 
-- Instead, we will handle "delivery" of original_url via a secure backend function or 
-- a separate table "purchases" that grants permission to read a storage path.
-- For simplicity in this schema, we assume application logic or a secure function retrieves the original_url.

-- 4. TRANSACTIONS
create table public.transactions (
  id uuid default uuid_generate_v4() primary key,
  buyer_id uuid references public.profiles(id) not null,
  photographer_id uuid references public.profiles(id) not null,
  amount numeric(10, 2) not null,
  commission_amount numeric(10, 2) not null,
  stripe_payment_intent_id text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Transactions
alter table public.transactions enable row level security;
create policy "Users can view their own transactions" on public.transactions for select using (auth.uid() = buyer_id or auth.uid() = photographer_id);


-- STORAGE BUCKETS SETUP (You might need to run this separately or manually in Dashboard)
-- Insert into storage.buckets
insert into storage.buckets (id, name, public) values ('public-photos', 'public-photos', true) on conflict do nothing;
insert into storage.buckets (id, name, public) values ('original-photos', 'original-photos', false) on conflict do nothing;

-- Storage Policies
-- PUBLIC PHOTOS: Viewable by everyone, Upload only by authenticated photographers
create policy "Public Photos View" on storage.objects for select using ( bucket_id = 'public-photos' );
create policy "Public Photos Upload" on storage.objects for insert with check ( bucket_id = 'public-photos' and auth.role() = 'authenticated' );

-- ORIGINAL PHOTOS: Private. Only uploader can view/upload initially. Buyer gets access via specialized logic (e.g., Signed URL generated by Edge Function).
create policy "Original Photos Upload" on storage.objects for insert with check ( bucket_id = 'original-photos' and auth.role() = 'authenticated' );
create policy "Photographer View Own Originals" on storage.objects for select using ( bucket_id = 'original-photos' and auth.uid() = owner );

-- TRIGGER for New User Profile
-- Automatically create a profile entry when a new user signs up via Supabase Auth
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', (new.raw_user_meta_data->>'role')::user_role);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
