-- SECURITY HARDENING: Storage Policies
-- This migration ensures strict access to original-photos bucket.

-- 1. Drop existing policies to start fresh
DROP POLICY IF EXISTS "Public Photos View" ON storage.objects;
DROP POLICY IF EXISTS "Public Photos Upload" ON storage.objects;
DROP POLICY IF EXISTS "Original Photos Upload" ON storage.objects;
DROP POLICY IF EXISTS "Photographer View Own Originals" ON storage.objects;

-- 2. PUBLIC PHOTOS: Viewable by everyone
CREATE POLICY "Public Photos View" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'public-photos' );

-- 3. PUBLIC PHOTOS: Upload only by authenticated photographers/admins
CREATE POLICY "Public Photos Upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( 
    bucket_id = 'public-photos' 
    AND auth.role() = 'authenticated'
    AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND role IN ('photographer', 'admin')
    )
);

-- 4. ORIGINAL PHOTOS: Strictly private
-- Only authenticated photographers can upload to original-photos
CREATE POLICY "Original Photos Upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( 
    bucket_id = 'original-photos' 
    AND auth.role() = 'authenticated'
    AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid()
        AND role IN ('photographer', 'admin')
    )
);

-- 5. ORIGINAL PHOTOS: Selection
-- Only the owner (photographer who uploaded) or an admin can see the original file.
-- Buyers will access via Signed URLs (generated by Edge Functions), which bypasses RLS.
CREATE POLICY "Original Photos Owner and Admin View" 
ON storage.objects FOR SELECT 
USING ( 
    bucket_id = 'original-photos' 
    AND (
        auth.uid() = owner 
        OR EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND role = 'admin'
        )
    )
);
